### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Radeon89** [metastork/sitePingDiff#1]
Hi.

I am sorry to contact you here but I am new and I did not a better way to do it.

I am looking for a tool that allow me to automatically monitor webpages. Examples of use: track the price of an item and check item availability.

Requirements:
1. track just a portion of a page, not the whole page.
2. Receive notifications in case of change on my phone (via email? no idea).
3. Possibility the customize the frequency of the checks

Does your tool allow this?

My intention would be to place this stuff in a raspberry, as it is cheap solution and it has a low power consumption. Is it in your opinion suitable for this?

Thanks

**Comment by protostork** [comment]
Hi @Radeon89, thanks for reaching out, and apologies for the delay, I had not seen your message until just now. I hope this information will still be useful.

Yes, the script should be able to fulfil at least some of your requirements, depending on the web-page that you are looking to monitor and depending on how much Javascript it uses. Regarding your individual questions:

1. Yes, the `searchWithinTag: div#id.class` setting in the config.yml file would allow you to just monitor part of a page.
2. Yes, it allows monitoring by email, but not currently by phone.
3. Yes, you can either specify the script to ping the site every N number of minutes or hours (though you'd manually have to set a cronjob or other script to invoke it at least every few minutes).

Power consumption should be pretty low and very much suitable for a Pi and it's fairly stable and reliable.

I have just pushed version 0.2 of this, which has some additional features and slightly more robust operations (including a shell script that terminates the script if it gets stuck for too long, which sometimes happens when there's limited internet connectivity - see the section on bugs in the Readme for more details on this).

Hope this helps if you haven't found another solution in the meantime - I hadn't found a good solution back then, which is why I had put this one together. If you have any questions, please let me know.
